# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UDP' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UDP
  pod 'CocoaAsyncSocket', '~> 7.6.5'
  target 'UDPTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UDPUITests' do
    # Pods for testing
  end

end
