# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios ,'12.0'

use_frameworks!

target 'MDNS' do
  # Comment the next line if you don't want to use dynamic frameworks
  
  # Pods for MDNS
  pod 'SnapKit'
  pod 'CocoaAsyncSocket', '~> 7.6.5'
  pod 'SwiftyJSON', '~> 5.0.0'
  pod 'Toast-Swift', '~> 5.0.0'
  target 'MDNSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MDNSUITests' do
    # Pods for testing
  end

end
